# docker-compose file intended for deployment of nginx and sninterface on openbot vm
version: "3.5"
services:
  nginx:
    image: hub.cs.upb.de/martenls/bachelor-thesis-code/nginx-openbot:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/ssl:/etc/nginx/ssl"
    networks:
      - compose_overlay
  sninterface-twitter:
    image: hub.cs.upb.de/martenls/bachelor-thesis-code/sninterface-botkit-twitter:latest
    container_name: sninterface-botkit-twitter
    restart: unless-stopped
    env_file: .env
    environment: 
      - QA_URL=http://qa-system:8080/qa
    networks:
      - compose_overlay
  sninterface-web:
    image: hub.cs.upb.de/martenls/bachelor-thesis-code/sninterface-botkit-web:latest
    container_name: sninterface-botkit-web
    restart: unless-stopped
    environment: 
      - QA_URL=http://qa-system:8080/qa
    networks:
      - compose_overlay
  qa-system:
    image: hub.cs.upb.de/martenls/bachelor-thesis-code/qa-system:latest
    container_name: qa-system
    restart: unless-stopped
    environment:
      - TEMPLATES_FILE=/qa/data/templates.txt
      - ONTOLOGY_FILE=/qa/data/dcat2+german-labels.rdf
      - LAUNUTS_FILE=/qa/data/launuts.ttl
      - SPARQL_ENDPOINT=http://fuseki:3030/opal/query
      - ES_HOST=elastic
    networks:
      - compose_overlay
  fuseki:
    image: stain/jena-fuseki:latest
    container_name: fuseki
    volumes:
      - "/srv/fuseki:/fuseki"
    environment: 
      - ADMIN_PASSWORD=pw123
    networks:
      - compose_overlay
  elastic:
    image: elasticsearch:7.7.0
    container_name: elastic
    restart: unless-stopped
    environment: 
      - "discovery.type=single-node"
    networks: 
      - compose_overlay

networks:
  compose_overlay:
    name: compose_overlay
    
