# docker-compose file intended for deployment of nginx and sninterface on openbot vm
version: "3.5"
services:
  sninterface-twitter:
    image: sninterface-botkit-twitter
    container_name: sninterface-botkit-twitter
    env_file: .env-templates/twitter.env
    environment: 
      - QA_URL=http://qa-system:8080/qa
    ports:
      - "3000:3000"
    networks:
      - compose_overlay
  sninterface-web:
    image: sninterface-botkit-web
    container_name: sninterface-botkit-web
    env_file: .env-templates/web.env
    environment: 
      - QA_URL=http://qa-system:8080/qa
    ports:
      - "3030:3030"
    networks:
      - compose_overlay
  qa-system:
    image: qa-system
    container_name: qa-system
    env_file: .env-templates/qa.env
    ports:
      - "8080:8080"
    networks:
      - compose_overlay
  # fuseki:
  #   image: stain/jena-fuseki:latest
  #   container_name: fuseki
  #   volumes:
  #     - "/fuseki"
  #   networks:
  #     - compose_overlay
  elastic:
    image: elasticsearch:7.7.0
    container_name: elastic
    environment: 
      - "discovery.type=single-node"
    networks: 
      - compose_overlay

networks:
  compose_overlay:
    name: compose_overlay
    
