# docker-compose file intended for deployment of nginx and sninterface on openbot vm
version: "3"
services:
  twitter-bot:
    image: twitter-bot
    container_name: twitter-bot
    env_file: .env-templates/twitter.env
    ports:
      - "3000:3000"
    networks:
      - compose_overlay
  web-bot:
    image: web-bot
    container_name: web-bot
    env_file: .env-templates/web.env
    ports:
      - "3030:3030"
    networks:
      - compose_overlay
  qa-system:
    depends_on: [elastic]
    image: qa-system
    container_name: qa-system
    env_file: .env-templates/qa.env
    ports:
      - "8080:8080"
    networks:
      - compose_overlay
  # fuseki:
  #   image: stain/jena-fuseki:latest
  #   container_name: fuseki
  #   volumes:
  #     - "/fuseki"
  #   networks:
  #     - compose_overlay
  elastic:
    image: elasticsearch:7.7.0
    container_name: elastic
    environment: 
      - "discovery.type=single-node"
    networks: 
      - compose_overlay

networks:
  compose_overlay:
    
    
