

es:
  host: 131.234.28.184
  port: 9200
  property_index: propdcat3
  class_index: classdcat3
  launuts_index: launuts

ontology:
  file: src/main/data/dcat2+german-labels.rdf

launuts:
  file: src/main/data/launuts.ttl

templates:
  file: src/main/data/templates.txt

sparql:
  endpoint: https://openbot.cs.upb.de/fuseki/opal/query

logging:
  level:
    com:
      martenls:
        DEBUG