

es:
  host: localhost
  port: 3030
  property_index: propdcat3
  class_index: classdcat3
  launuts_index: launuts
  language_index: lang

ontology:
  file: src/data/dcat2+german-labels.rdf

launuts:
  file: src/data/launuts.ttl

templates:
  file: src/data/templates.txt

languages:
  file: src/data/languages-skos-ap-act.rdf

sparql:
  endpoint: https://openbot.cs.upb.de/fuseki/opal/query

logging:
  level:
    com:
      martenls:
        DEBUG