es:
  host: localhost
  port: 3030
  property_index: dcatprops
  launuts_index: launuts
  language_index: languages
  theme_index: themes
  license_index: licenses
  frequency_index: frequencies
  filetype_index: filetypes

data:
  dir: src/data
  ontology: ${data.dir}/dcat+labels.json
  launuts: ${data.dir}/launuts.json
  templates: ${data.dir}/templates.txt
  languageEntities: ${data.dir}/languages.json
  themeEntities: ${data.dir}/themes.json
  licenseEntities: ${data.dir}/licences.json
  frequencyEntities: ${data.dir}/frequencies.json
  filetypeEntities: ${data.dir}/filetypes.json

sparql:
  endpoint: https://openbot.cs.upb.de/fuseki/opal2020-07/query

properties:
  languages: "en, de"
  noCatalogFix: false

logging:
  level:
    com:
      martenls:
        DEBUG