

es:
  host: localhost
  port: 3030
  property_index: dcatprops
  launuts_index: launuts
  language_index: lang
  theme_index: themes
  license_index: licenses


ontology: src/data/dcat+labels.json

launuts: src/data/launuts.ttl

templates: src/data/templates.txt

languageEntities: src/data/languages-skos-ap-act.rdf

themeEntities: src/data/data-theme-skos-ap-act.rdf

licenseEntities: src/data/licences-skos-ap-act.rdf

sparql:
  endpoint: https://openbot.cs.upb.de/fuseki/opal/query

properties:
  languages: "en, de"

logging:
  level:
    com:
      martenls:
        DEBUG