

es:
  host: localhost
  port: 3030
  property_index: dcatprops
  launuts_index: launuts
  language_index: lang
  theme_index: themes
  license_index: licenses


data-path: src/data

ontology: ${data-path}/dcat+labels.json

launuts: ${data-path}/launuts.ttl

templates: ${data-path}/templates.txt

languageEntities: ${data-path}/languages-skos-ap-act.rdf

themeEntities: ${data-path}/data-theme-skos-ap-act.rdf

licenseEntities: ${data-path}/licences-skos-ap-act.rdf

sparql:
  endpoint: https://openbot.cs.upb.de/fuseki/opal/query

properties:
  languages: "en, de"

logging:
  level:
    com:
      martenls:
        DEBUG